services:
  - type: web
    name: movie-recommender-flask
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: TMDB_API_KEY
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CACHE_DIR
        value: /opt/render/.cache